### ISSUE TITLE
Standort Abfrage

### ISSUE THREAD

**Issue by RysingTV** [MacSchierer/Covid-19_Ampel#1]
Wie würde es mit einer Standort Abfrage das der die Region automatisch erkennt? Hätt doch was.

**Comment by MacSchierer** [comment]
Hi! Ja, das hätte was. Ich schau mal, wie und wann ich das umsetzen kann.

**Comment by RysingTV** [comment]
Da gibt es ja schon eins was mit dem Standort arbeitet. Hat halt den Vorteil wenn man in einen Anderen Kreis fährt, sieht man den Kreis in dem man sich befindet.

**Comment by MacSchierer** [comment]
Die Region wird jetzt optional per GPS ermittelt. Dafür einfach den Widgetparameter leer lassen.
Für das Anzeigen mehrerer Widgets mit unterschiedlichen Regionen, kann weiterhin die OBJECTID verwendet werden.
