### ISSUE TITLE
Änderung des RKI COVID-19 Datensatzes

### ISSUE THREAD

**Issue by 2Qt2beStr8** [MacSchierer/Covid-19_Ampel#10]
Guten Morgen,

das RKI hat den Datensatz geändert und somit funktioniert leider dein Widget nicht mehr.
Wirst du es evlt. anpassen?

https://arcgis.esri.de/aenderung-des-rki-covid-19-datensatzes/

Gruß
DJ

**Comment by MacSchierer** [comment]
Moin,
schaue ich mir im Laufe des Tages mal an und versuche es zu korrigieren. Danke für den Hinweis.

**Comment by 2Qt2beStr8** [comment]
Kein Problem und schon mal danke für deine Mühe

**Comment by MacSchierer** [comment]
Hallo DJ,
ich habe die URL für den API-Endpunkt jetzt angepasst.
Das Scriptable sollte jetzt wieder wie gewohnt Daten des RKI anzeigen.
