### ISSUE TITLE
Fehlermeldung - Error on line 11

### ISSUE THREAD

**Issue by frollein-ike** [MacSchierer/Covid-19_Ampel#8]
![CBBE88FF-EE2B-48E3-B280-DB6EDF811B5D](https://user-images.githubusercontent.com/73532633/115408792-72ca8f80-a1f1-11eb-8c27-e7d7c21b4e04.jpeg)
 
 Siehe Screenshot - Das Widget funktioniert weder auf meinem iPhone noch auf dem iPad - irgendeine Idee, was ich falsch mache? (Iphone12, iOS 14.4.2)

Gruß von Frollein Ike

**Comment by MacSchierer** [comment]
Hallo Frollein Ike,

das ist seltsam. In Zeile 11 steht nur ein Kommentar ohne Funktion zur App. 
Vielleicht ist das Zeichen beim Kopieren/Einfügen dort "reingerutscht".
Lad dir das Script mal neu in die App.

Grüße!

**Comment by frollein-ike** [comment]
Ich habe den Fehler gefunden: ich habe das Skript über Scriptdude installiert, und dabei läuft was schief, es wird nämlich die .js-Datei als Skript eingeführt, nicht das wirkliche Skript. Und da ich wenig Ahnung von sowas habe (um nicht zu sagen gar keine 🙈), ist mir das natürlich nicht aufgefallen. Jetzt habe ich das Skript manuell eingefügt und alles läuft wie es soll. Vielen Dank!
