### ISSUE TITLE
Error on line 11…

### ISSUE THREAD

**Issue by mibaxx** [MacSchierer/Covid-19_Ampel#9]
Ich bekomme das Script nicht zum Laufen. Egal ob mit Parameter (OBJECTID) oder ohne.

Es erscheint nur die Fehlermeldung:

![9EB646D1-AD61-4F3B-8EA2-FD1AA2DA9265](https://user-images.githubusercontent.com/93615504/139936919-f81627ab-2963-4af7-8950-9f9d4c4b3759.jpeg)

ich verwende ein iPhone 13 Pro mit iOS 15.1

Was mache ich falsch?

Liebe Grüße
Michael

**Comment by MacSchierer** [comment]
Hallo,

vermutlich ist das Skript nicht vollständig in Scriptable übernommen worden.
Vielleicht beim Copy/Paste etwas vergessen. Kommt auch schon mal beim verwenden von scriptdu.de vor.
Am besten einfach nochmal neu einfügen.

**Comment by mibaxx** [comment]
Danke für die schnelle Antwort. 👍🏻

Bei der Installation via ScriptDu.de fügt dieses eine erste Zeile mit ein und die stört den Ablauf des Skripts. Ich habe (wie von dir vorgeschlagen) das Skript via Copy & Paste eingefügt und nun läuft es hervorragend.

Nochmals vielen Dank! 😀

Mein Issue kann nun geschlossen werden.
